### ISSUE TITLE
Cannot test your sample project

### ISSUE THREAD

**Issue by tieubao** [pjakubczyk/robospock-plugin#13]
I clone your repository and import it to Android Studio. Then I run `./gradlew robospock` in terminal and get this error:

![screen shot 2014-10-15 at 9 17 27 am](https://cloud.githubusercontent.com/assets/1749624/4639664/d9100caa-5411-11e4-865b-e35920447f80.png)

**Comment by pjakubczyk** [comment]
At this moment I'm not supporting the plugin since google changes the API quite frequent. Anyways @pelotasplus created bunch of tutorials where you can test using Robospock but without the plugin https://github.com/pelotasplus/RoboSpock-tutorial

**Comment by tieubao** [comment]
@pjakubczyk thank you for your reply. I checked RoboSpock-tutorial and completed setting up my project.
